[mysql]
  dbname    = "howareyou"
  host      = "localhost"
  port      = 3306
  user      = "root"
  pass      = "root"
  sslmode   = "false"
  blacklist = [
    "user_group.created_at",
    "user_group.updated_at",
  ]
